source 'https://rubygems.org'

gem 'rails', '3.2.22.5'

gem 'nokogiri', '1.6.8'

gem 'sqlite3'

gem 'jquery-rails'

gem "bugsnag"

gem "warden"

group :dj, optional: true do
    gem "delayed_job"
    gem "delayed_job_active_record"
end
